// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate/introspect) needs the unpooled connection — the pooler
    // runs in transaction mode, which doesn't support the advisory locks
    // migrate uses. The app itself connects via DATABASE_URL (pooled) at
    // runtime through @prisma/adapter-neon, not through this config.
    url: process.env["DIRECT_URL"],
  },
});
